# .gitlab-ci.yml
image: node:lts-alpine

before_script:
  - yarn install --cache-folder .yarn

test:
  stage: test
  script:
      - yarn test
  cache:
    paths:
    - node_modules/
    - .yarn

build:
  stage: build
  script:
      - yarn build
  cache:
    paths:
    - node_modules/
    - .yarn